import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const formatBackground = () => {
    return "from-yellow-700 to-orange-700";
  };
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
